### ISSUE TITLE
弱弱问一下我的理解对不？

### ISSUE THREAD

**Issue by yuyang** [ngaut/builddatabase#11]
申明：
1. 基本不懂go
2. 有那么一丢丢数据库基础
3. 听说tidb一段时间，看代码只是过去的这几十分钟。。。
so 说错了问错了，权当我搞笑

目前的理解/问题
1. storage 层用hbase或者sstable的各种亲戚？有没有考虑采用类似innodb的storage。
2. execute那一层就是 https://github.com/pingcap/tidb/blob/master/executor/executor.go 里面那些executor是吗？
3. cost模型ms很简单？https://github.com/pingcap/tidb/blob/master/optimizer/plan/cost.go 是我看漏了，还是就是这些？
4. parser.y 和parser.go 哪个是自动生成的？
5. optimize的是rule base的？cost base的？还是both的？rule engine在哪儿？建议我从哪里看起呢？
6. 是打算是实现sql标准？还是兼容mysql？
7. 数据字典在哪里定义的？https://github.com/pingcap/tidb/tree/master/table？保存在哪儿？kv？还是像hive搞个mysql存
8. 能开源点稍微详细点的文档吗？

您有空回答一下

猴年大吉，越来越好

国内安心做数据库的人不多啊。。。

**Comment by ngaut** [comment]
1. storage 层用hbase或者sstable的各种亲戚？有没有考虑采用类似innodb的storage。
   后面有个抽象的接口，早期最先支持rocksdb，如有兴趣可以添加自己的engine
2. execute那一层就是 https://github.com/pingcap/tidb/blob/master/executor/executor.go 里面那些executor是吗？
   是
3. cost模型ms很简单？https://github.com/pingcap/tidb/blob/master/optimizer/plan/cost.go 是我看漏了，还是就是这些？
   目前还比较简单，正在优化
4. parser.y 和parser.go 哪个是自动生成的？
   parser.go
5. optimize的是rule base的？cost base的？还是both的？rule engine在哪儿？建议我从哪里看起呢？
   目前是rule base的
6. 是打算是实现sql标准？还是兼容mysql？
   兼容mysql
7. 数据字典在哪里定义的？https://github.com/pingcap/tidb/tree/master/table？保存在哪儿？kv？还是像hive搞个mysql存
   kv
8. 能开源点稍微详细点的文档吗？
   正在逐步完善

感谢关注

**Comment by yanyiwu** [comment]
回复简直神速啊。

**Comment by yuyang** [comment]
赞~~~
